#include QMK_KEYBOARD_H
#include "keymap_italian.h"

enum {
    TD_ANG,
    TD_E,
    TD_BRC,
    TD_BKT,
    TD_PAR,
    TD_CUR,
};

qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_ANG] =  ACTION_TAP_DANCE_DOUBLE(IT_LABK, IT_RABK),
    [TD_E] =    ACTION_TAP_DANCE_DOUBLE(IT_EGRV, IT_EACU),
    [TD_BRC] =  ACTION_TAP_DANCE_DOUBLE(IT_LCBR, IT_RCBR),
    [TD_BKT] =  ACTION_TAP_DANCE_DOUBLE(IT_LBRC, IT_RBRC),
    [TD_PAR] =  ACTION_TAP_DANCE_DOUBLE(IT_LPRN, IT_RPRN),
    [TD_CUR] =  ACTION_TAP_DANCE_DOUBLE(IT_DLR, IT_EURO),
};


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define DEFAULT                 0
#define UTILITY                 1
#define SYMBOLS                 2
#define NUM_FUNC                3
#define KEYBOARD                4
#define QWERTY                  5
#define GAMING                  6
#define EXTRA                   7

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[DEFAULT] = LAYOUT_split_3x5_2(
        KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_BSPC,
        KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O,
        LSFT_T(KC_Z), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_D), KC_V, KC_K, LGUI_T(KC_H), LALT_T(IT_COMM), LCTL_T(IT_DOT), LSFT_T(IT_QUOT),
                             LT(2,KC_ENT), MO(7), MO(4), LT(1,KC_SPC)),

	[UTILITY] = LAYOUT_split_3x5_2(
        KC_ESC, KC_PSCR, CAPSWRD, KC_CAPS, KC_INS, KC_PGUP, KC_HOME, KC_END, KC_END, KC_DEL,
        KC_TAB, OSM(MOD_LALT), OSM(MOD_LCTL), OSM(MOD_LSFT), OSM(MOD_LGUI), LALT(KC_TAB), KC_LEFT, KC_UP, KC_DOWN, KC_RGHT,
        LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), RCS(KC_Z), KC_PGDN, RCS(KC_TAB), LCA(KC_LEFT), LCA(KC_DOWN), LCTL(KC_TAB),
                             MO(3), KC_NO, KC_NO, KC_NO),

	[SYMBOLS] = LAYOUT_split_3x5_2(
        IT_EXLM, IT_DQUO, IT_AGRV, IT_UGRV, IT_CIRC, IT_BSLS, IT_AT, IT_HASH, IT_QUES, LCTL(KC_BSPC),
        TD(TD_ANG), IT_IGRV, IT_OGRV, TD(TD_E), IT_DEG, TD(TD_CUR), IT_EQL, IT_SLSH, IT_MINS, IT_UNDS,
        IT_PERC, TD(TD_BRC), TD(TD_BKT), TD(TD_PAR), RALT(KC_EQL), RALT(KC_MINUS), IT_AMPR, IT_PIPE, IT_ASTR, IT_PLUS,
                             KC_NO, KC_NO, KC_NO, MO(3)),

	[NUM_FUNC] = LAYOUT_split_3x5_2(
        KC_DOT, KC_7, KC_8, KC_9, KC_NO, KC_F10, KC_F7, KC_F8, KC_F9, KC_BSPC, KC_0, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_COMM, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO),

	[KEYBOARD] = LAYOUT_split_3x5_2(
        QK_BOOT, DB_TOGG, KC_VOLD, KC_VOLU, KC_WH_U, KC_ACL2, KC_BRIU, KC_BRID, DB_TOGG, QK_BOOT,
        KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT, KC_NO, KC_ACL1, KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R,
        KC_NO, KC_BTN5, KC_BTN4, KC_BTN3, KC_WH_D, KC_ACL0, TO(5), TO(6), KC_BTN1, KC_BTN2,
                             KC_BTN1, KC_BTN2, KC_TRNS, KC_NO),

	[QWERTY] = LAYOUT_split_3x5_2(
        KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_K, KC_O, KC_P,
        KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_BSPC,
        KC_Z, KC_X, KC_C, KC_V, KC_B, KC_M, KC_N, KC_COMM, KC_DOT, LSFT(KC_MINS),
                             KC_SPC, TO(0), TO(0), KC_ENT),

	[GAMING] = LAYOUT_split_3x5_2(
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O,
        KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_J, KC_K, KC_L, KC_P,
        KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_M, KC_N, KC_NO, KC_NO,
                            KC_SPC, KC_ESC, TO(0), KC_ENT),

	[EXTRA] = LAYOUT_split_3x5_2(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                            KC_NO, KC_TRNS, KC_NO, KC_NO)
};

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_Z):
        case LSFT_T(IT_QUOT):
            return 160;
        case LT(2, KC_ENT):
            return 125;
        default:
            return TAPPING_TERM;
    }
};


